# Generated by Django 4.2.4 on 2023-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ddn', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('nombre_page', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('date_parution', models.DateField()),
                ('couverture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
