# Generated by Django 4.2.4 on 2023-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0002_auteur_livre_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteurs',
            field=models.ManyToManyField(to='meslivres.auteur'),
        ),
    ]
