# Generated by Django 4.2.4 on 2023-08-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0003_livre_auteurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='./image'),
        ),
    ]
