# Generated by Django 4.2.4 on 2023-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0004_genre_alter_livre_couverture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='genre',
        ),
        migrations.AddField(
            model_name='livre',
            name='genres',
            field=models.ManyToManyField(to='meslivres.genre'),
        ),
    ]
