# Generated by Django 4.2.4 on 2023-08-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0005_remove_livre_genre_livre_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='genres',
        ),
        migrations.AddField(
            model_name='livre',
            name='genres',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
