# Generated by Django 4.2.4 on 2023-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meslivres', '0008_remove_livre_genres_delete_genre_livre_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
    ]
